version: "3.7"

services:
  backend:
    build: ./backend
    restart: always
    command: uvicorn main:app --host 0.0.0.0 --port 80
    labels: # Dynamic configurations
      # Enable Traefik for this service, to make it available in the public network
      - traefik.enable=true
      # Define the port inside of the Docker service to use
      - traefik.http.services.app.loadbalancer.server.port=80
      # Make Traefik use this domain in HTTP
      - traefik.http.routers.app-http.entrypoints=http
      - traefik.http.routers.app-http.rule=Host(`infundy.com`)
      # Use the traefik-public network (declared below)
      - traefik.docker.network=traefik-public
    networks:
      # Use the public network created to be shared between Traefik and
      # any other service that needs to be publicly available with HTTPS
      - traefik-public

networks:
  # Use the previously created public network "traefik-public", shared with other
  # services that need to be publicly available via this Traefik
  traefik-public:
    external: true
